#!/usr/bin/env bash
#script that displays the time for 12 hours and 59 minutes
#display hours from 0 to 12
#display minutes from 0 to 59
hr=0
while [ $hr -le 12 ]
do
	echo "Hour: $hr"
	min=1
	while [ $min -le 59 ]
	do
		echo "$min"
		min=$((min+1))
	done
	hr=$((hr+1))
done
